### ISSUE TITLE
Validator should support empty-text annotations

### ISSUE THREAD

**Issue by tarkvara** [IIIF/presentation-api#7]
Our software often generates annotations like the following, with empty text as the content, representing a transcription line which hasn't been entered yet.  The validator complains "Text must have either a URI or embedded text", but it should really accept this as valid.
{
   "@id" : "http://t-pen.org/Paris%2C+Petrus+Plaoul+Reims+1/line/100173639",
   "@type" : "oa:Annotation",
   "motivation" : "sc:painting",
   "resource" : {
      "@type" : "cnt:ContentAsText",
      "chars" : ""
   },
   "on" : "http://t-pen.org/Paris%2C+Petrus+Plaoul+Reims+1/canvas/R1r.jpg#xywh=89,125,248,15"
}

**Comment by azaroth42** [comment]
Fixed.
